# Generated by Django 4.1.6 on 2023-02-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='basic_metabolism',
            field=models.IntegerField(null=True, verbose_name='Базовый обмен веществ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.BooleanField(null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.IntegerField(null=True, verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='physical_activity',
            field=models.IntegerField(default=2, verbose_name='Уровень физической активности'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.IntegerField(null=True, verbose_name='Вес'),
        ),
    ]
