# Generated by Django 4.1.6 on 2023-02-25 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_profile_basic_metabolism_alter_profile_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
