# Generated by Django 4.1.6 on 2023-02-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='day_of_week',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='meal',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
