# Generated by Django 4.1.6 on 2023-05-16 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0017_alter_useringredient_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='active_cooking_time',
            field=models.IntegerField(null=True, verbose_name='Активное время приготовления'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='calories',
            field=models.IntegerField(null=True, verbose_name='Энергетическая ценность'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_name',
            field=models.CharField(max_length=255, verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='href',
            field=models.CharField(max_length=255, unique=True, verbose_name='Ссылка на рецепт'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.CharField(max_length=255, null=True, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='portions_count',
            field=models.IntegerField(null=True, verbose_name='Количество порций'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='tags',
            field=models.ManyToManyField(to='food.tag', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='total_cooking_time',
            field=models.IntegerField(null=True, verbose_name='Общее время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.dish', verbose_name='Блюдо'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food.ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='measure_unit',
            field=models.CharField(max_length=255, null=True, verbose_name='Единицы измерения'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='note',
            field=models.CharField(max_length=255, null=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='quantity',
            field=models.FloatField(verbose_name='Количество'),
        ),
        migrations.CreateModel(
            name='IngredientBlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.ingredient')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DishBlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.dish')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
